<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Mon, 31 Dec 2012 01:31:50 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'addon_changeurlbywas33m' => 
  array (
    'is_setup' => '1',
  ),
  'addon_permissioncheck' => 
  array (
    'is_setup' => '1',
  ),
  'addon_facebookoptimizerbywas33m' => 
  array (
    'is_setup' => '1',
  ),
  'addon_galleryeditorbywas33m' => 
  array (
    'is_setup' => '1',
  ),
  'addon_orderxml' => 
  array (
    'is_setup' => '1',
    'orderstatus' => 'all',
  ),
  'addon_ysm' => 
  array (
    'is_setup' => '1',
  ),
);
