<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Mon, 18 Feb 2013 17:21:29 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_nab' => 
  array (
    'is_setup' => '1',
    'displayname' => 'NAB',
    'vendor_name' => 'SM70010',
    'email' => 'cyclingwear@seightcustom.com.au',
    'testmode' => 'NO',
  ),
);
