<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Sat, 05 May 2012 01:52:58 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'default' => '1',
  1 => 
  array (
    'customergroupid' => '1',
    'groupname' => 'Seight Customer Group',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '1',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  2 => 
  array (
    'customergroupid' => '2',
    'groupname' => 'MyTeamShop - Adelalaie Cyclists',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'specific',
    'accesscategories' => 
    array (
      0 => '10',
      1 => '11',
      2 => '12',
      3 => '13',
      4 => '14',
      5 => '15',
      6 => '18',
      7 => '19',
      8 => '20',
      9 => '21',
      10 => '33',
    ),
  ),
);
