<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Mon, 30 Apr 2012 10:48:01 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => '1',
  1 => '1',
  2 => '1',
);
