<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Mon, 17 Jun 2013 10:09:38 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'emailintegration_emailmarketer' => 
  array (
    'url' => 'http://seightcustom.com.au/emailmarketer/xml.php',
    'username' => 'admin',
    'usertoken' => 'a571c5d2cbc6b0279155425307beb246e621a0a6',
    'isconfigured' => '1',
    'last_list_update' => '1335866128',
  ),
);
