<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Sat, 08 Dec 2012 08:48:46 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'notification_email' => 
  array (
    'is_setup' => '1',
    'emailaddress' => 'tristan@seightcustom.com.au',
  ),
);
