<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Wed, 12 Jun 2013 02:31:04 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    5 => 
    array (
      'pagetitle' => 'Info',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '5',
      'pagecustomersonly' => '0',
    ),
    6 => 
    array (
      'pagetitle' => 'Gallery',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '6',
      'pagecustomersonly' => '0',
    ),
    7 => 
    array (
      'pagetitle' => 'Community',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '7',
      'pagecustomersonly' => '0',
    ),
    9 => 
    array (
      'pagetitle' => 'Contact Us',
      'pagetype' => '3',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '9',
      'pagecustomersonly' => '0',
    ),
  ),
  5 => 
  array (
    14 => 
    array (
      'pagetitle' => 'About Us',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '14',
      'pagecustomersonly' => '0',
    ),
    17 => 
    array (
      'pagetitle' => 'Artwork',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '17',
      'pagecustomersonly' => '0',
    ),
    19 => 
    array (
      'pagetitle' => 'Garment Technology',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '19',
      'pagecustomersonly' => '0',
    ),
    20 => 
    array (
      'pagetitle' => 'Guarantee',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '20',
      'pagecustomersonly' => '0',
    ),
    15 => 
    array (
      'pagetitle' => 'How To Order',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '15',
      'pagecustomersonly' => '0',
    ),
    29 => 
    array (
      'pagetitle' => 'Price Beat Policy',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '29',
      'pagecustomersonly' => '0',
    ),
    21 => 
    array (
      'pagetitle' => 'Price List / Minimums',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '21',
      'pagecustomersonly' => '0',
    ),
    22 => 
    array (
      'pagetitle' => 'Samples',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '22',
      'pagecustomersonly' => '0',
    ),
    18 => 
    array (
      'pagetitle' => 'Size Charts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '18',
      'pagecustomersonly' => '0',
    ),
    16 => 
    array (
      'pagetitle' => 'Templates',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '5',
      'pageid' => '16',
      'pagecustomersonly' => '0',
    ),
  ),
  7 => 
  array (
    31 => 
    array (
      'pagetitle' => 'Charity Rides & Events',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '7',
      'pageid' => '31',
      'pagecustomersonly' => '0',
    ),
    25 => 
    array (
      'pagetitle' => 'Community Groups',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '7',
      'pageid' => '25',
      'pagecustomersonly' => '0',
    ),
    24 => 
    array (
      'pagetitle' => 'Sponsored Riders',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '7',
      'pageid' => '24',
      'pagecustomersonly' => '0',
    ),
    23 => 
    array (
      'pagetitle' => 'Sponsorship Program',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '7',
      'pageid' => '23',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => 
  array (
    'pageid' => '10',
    'pagetitle' => 'Home',
    'pagemetatitle' => 'Seight Custom Cycling Wear | Custom Cycling Clothing | Home',
    'pagelink' => 'http://',
    'pagefeed' => 'http://',
    'pageemail' => 'tristan@seightcustom.com.au',
    'pagecontent' => '<div class="wide">
<h1 style="text-align: center;"><span style="color: #000000;">Make&nbsp;it Happen with <a href="http://www.seightcustom.com.au/custom/Products" target="_self">Seight Custom Cycling Wear</a></span></h1>
</div>
<p style="width: 960px;">Seight Custom Cycling Wear are revolutionising <a href="http://www.seightcustom.com.au/custom/products/jerseys/"><span style="color: #000000;">custom cycling clothing</span></a> in Australia, providing a level of service and quality superior to our competitors. Our customers come from far and wide across Australia, from major cities such as Adelaide, Brisbane, Melbourne, Perth and Sydney, to the smaller country towns. Located in Glen Iris, Victoria, Australia, Seight is a premium <a href="http://www.seightcustom.com.au/custom/products/jerseys/"><span style="color: #000000;">custom cycling apparel</span></a> provider to the Australian and Worldwide markets. Our entire product range, from custom cycling jerseys to shirts, shorts, and shoes, is driven by performance, quality and fit whilst being price friendly.</p>
<p style="width: 960px;"><a href="http://www.seightcustom.com.au/custom/products/jerseys/"><span style="color: #000000;">Seight Custom Cycling Wear</span></a> produces cycling shorts, bike jerseys, bib shorts and tights, tri suits, vests &amp; jackets, arm &amp; leg warmers and other Australian custom cycling clothing specifically designed for racing, training, and casual wear. If you are looking for custom made cycling jerseys, with no minimum order requirements, then look no further than Seight. Additionally, all our customised jerseys and custom cycling apparel qualify for our Price Beat Policy. You will not find better customer service, price and quality when shopping for <a href="http://www.seightcustom.com.au/custom/products/jerseys/"><span style="color: #000000;">custom cycling jerseys</span></a> in Australia.</p>',
    'pagestatus' => '0',
    'pageparentid' => '0',
    'pagesort' => '0',
    'pagekeywords' => 'custom bike jersey, custom cycling clothings, custom cycling jerseys, customized cycling jerseys, team, Seight, Custom, Cycling, Wear, cycling, clothing, custom, jerseys, wear, apparel, bike, clothes, jerseys, knicks, bib, apparel, shorts, customized, elite, skinsuit, personalized, crew, shirts, australia, team',
    'pagedesc' => 'Seight Custom Cycling Wear is home to the highest quality and most comfortable Custom Cycling Clothing and Custom Cycling Apparel in Australia.',
    'pagetype' => '0',
    'pagecontactfields' => '',
    'pagemetakeywords' => '',
    'pagemetadesc' => '',
    'pageishomepage' => '1',
    'pagelayoutfile' => '_page.html',
    'pageparentlist' => '10',
    'pagecustomersonly' => '0',
    'pagevendorid' => '0',
    'page_enable_optimizer' => '0',
    'pagensetleft' => '7',
    'pagensetright' => '8',
    'pagesearchkeywords' => '',
    'pagename' => 'home',
  ),
);
