<?php

/** Unreal Shopping Cart Data Store File **
  *
  * Generated: Thu, 30 May 2013 02:27:25 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    33 => 
    array (
      'categoryid' => '33',
      'catparentid' => '0',
      'catname' => 'Tiffany Jane',
      'catdepth' => '0',
    ),
    14 => 
    array (
      'categoryid' => '14',
      'catparentid' => '0',
      'catname' => 'MyTeamShop',
      'catdepth' => '0',
    ),
    13 => 
    array (
      'categoryid' => '13',
      'catparentid' => '0',
      'catname' => 'Products',
      'catdepth' => '0',
    ),
  ),
);
